### PR TITLE
Fix parsing on regtest network

### PR DESCRIPTION
**Pull request by MrHash**
Fixes issue where regtest network notifications were being parsed as mainnet format.

### CODE REVIEW

**Comment by larafale** [comment]
Hello @MrHash  thanks for the contribution :) 

I have not tested any regtest logic yet, only mainnet & testnet.
in that particular case the network variable is only used as a parameter for the `Address.fromOutputScript(el.script, network)` function (line 84), which is a provided by the `bitcoin-js` lib. 

so looking at your change :
```js
network == 'mainnet' ? networks.mainnet : networks.testnet
```
The problem is that `networks.mainnet` does not exists, the key we should point to is `bitcoin` instead. The `fromOutputScript` function accept a network object from the bitcoin-js `networks` object. Check the code https://github.com/bitcoinjs/bitcoinjs-lib/blob/ee694a3de1078f6558595403bd6169fb33ba7e59/src/networks.js

I suggest we keep and use the variable `network` in the codebase as a `string` (mainnet, testnet, regtest). This will make it a lot easier to reason about. And for the `fromOutputScript` function pass a proxy instead. ex:

```js
// proxy network (mainnet, testnet, regtest) to corresponding bitcoinjs-lib network object
const networkProxy = networks[({
    mainnet: 'bitcoin'
  , testnet: 'testnet'
  , regtest: 'testnet'
})[network]]

Address.fromOutputScript(el.script, networkProxy)
```

what do you think ?

**Comment by MrHash** [comment]
Ha I assumed that the network would be called `mainnet` but obviously making assumptions like that is a bad idea!

I think having the internal consistency is good so i'm fine with your solution.

**Comment by larafale** [comment]
it's not a bad idea, until it is :) 
i'll leave it like that until someone dig in regtest. probably overkill for this lib.
thanks

**Comment by MrHash** [comment]
Well actually i was using regtest that's why I had the problem.. but i can work around.

**Comment by larafale** [comment]
Oh ok. If it worked for you using `network=regtest` that used the underlaying value to `networks.testnet`, then regtest will work by settings `network=testnet`

**Comment by MrHash** [comment]
ok yeh that makes sense i'll try that

**Pull request closed without merging**
